FROM linkitaly/govway:3.3.16.p1_batch_postgres
# Copio librerie providers cloud
COPY cloud/azure/lib/ /jdbclibs/azure/
# Copio licenze associate alle librerie distribuite
COPY cloud/*/third-party-licenses* /usr/share/licenses/third-party-licenses/