FROM linkitaly/govway:3.3.16.p1_batch_postgres

COPY scripts/run_batch.sh /usr/local/bin/
RUN chown -R root:0 /usr/local/bin/run_batch.sh \
&& chmod ug=rx  /usr/local/bin/run_batch.sh


# Copio librerie providers cloud
COPY cloud/azure/lib/ /jdbclibs/azure/
COPY cloud/aws/lib/ /jdbclibs/aws/

# Copio licenze associate alle librerie distribuite
COPY cloud/*/third-party-licenses* /usr/share/licenses/third-party-licenses/

