# Default values for govway-fse-gtw-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 10

govway:
  popDbSkip: FALSE
  readyDbCheckSkip: TRUE
  defaultEntityName: "SOGEI"
  #jdbcPath: "/mnt/jars"
  serviceName: "GovWay-Manager"
  loggingLevel: "Trace"
  logLevel: "error"
  runService: ""
  
image:
  registry:
    urlGovWay: "linkitaly"
    repositoryGovWay: "govway-fse-gtw"
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  # tag: "master_manager_postgres"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


jdbcLibs: "/jdbclibs"

cloudProvider: aws  # Valori supportati: aws, azure

providerConfig:
  aws:
    storageClassName: "efs-sc"
    secretProviderName: "aws"
    secretsType: "secretsmanager"
    routeEnabled: false
    serviceType: "LoadBalancer"
  azure:
    storageClassName: "azure-file-fse"
    secretProviderName: "azure"
    secretsType: "secret"
    routeEnabled: true
    serviceType: "ClusterIP"

    


  
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  protocol: TCP


ingress:
 className: ""
 annotations: {}
   # kubernetes.io/ingress.class: nginx
   # kubernetes.io/tls-acme: "true"
 hosts: []
 tls: []
 #  - secretName: chart-example-tls
 #    hosts:
 #      - chart-example.local

containers:
  livenessProbe:
    port: 8080
    failureThreshold: 3
    initialDelaySeconds: 300
    periodSeconds: 5
  readinessProbe:
    path: /govwayConsole
    port: 8080
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 3

secrets:
  keyvaultName: ""  # <Your-KeyVault-Name> Insert the name of your Azure Key Vault
  tenantId: ""  # Azure Tenant ID
  secretKeyVaultName: ""  # The name of the secret you want to retrieve from Azure Key Vault
  iamrole: "" # The IAM role to use for IRSA authentication (AWS only)

resources:
  limits:
    cpu: 3
    memory: 6Gi
  requests:
    cpu: 3
    memory: 6Gi

autoscaler:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  cpuUtilization: 80
  #memoryUtilization: 80

nodeSelector: {}

tolerations: []

affinity: {}

# storage:
#   skuName: Premium_LRS  # Change to Premium_LRS if needed
