apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.fullname" . }}-cm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-1"
data:
  govway_local.properties: |
{{ .Files.Get "files/govway_local.properties" | indent 4 }}
  ocsp.properties: |
{{ .Files.Get "files/ocsp.properties" | indent 4 }}
  govway.fileTrace.properties: |
{{ .Files.Get "files/govway.fileTrace.properties" | indent 4 }}
  govway.fileTrace.log4j2.properties: |
{{ .Files.Get "files/govway.fileTrace.log4j2.properties" | indent 4 }}
