{{- include "govway_fse_gtw.validateCloudProvider" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}-cm
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-1"
data:
{{- $govway_local_properties := printf "files/govway_local.properties.%s" .Values.cloudProvider }}
  govway_local.properties: |
{{ .Files.Get $govway_local_properties | indent 4 }}
  ocsp.properties: |
{{ .Files.Get "files/ocsp.properties" | indent 4 }}
  govway.fileTrace.properties: |
{{ .Files.Get "files/govway.fileTrace.properties" | indent 4 }}
  govway.fileTrace.log4j2.properties: |
{{ .Files.Get "files/govway.fileTrace.log4j2.properties" | indent 4 }}
