{{- include "govway_fse_gtw.validateCloudProvider" . }}
{{- if not (index .Values.providerConfig .Values.cloudProvider "route.enabled") }}
{{- $serviceName :=  (include "govway_fse_gtw.fullname" . ) -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: v1
kind: Ingress
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}
  labels:
    {{- include "govway_fse_gtw.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /govway/rest/in/
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}