{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "service.fullname" . }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  path: /govway/rest/in/
  port:
    targetPort: {{ .Values.service.port }}-{{ .Values.service.protocol | lower }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "service.fullname" . }}
{{- end }}