apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "service.fullname" . }}-azure-keyvault-secrets
spec:
  provider: azure
  secretObjects:
    - secretName: {{ include "service.fullname" . }}-gtw-secrets
      type: Opaque
      data:
        - key: app-name
          objectName: app-name
        - key: app-id-{{ include "service.fullname" . }}
          objectName: app-id
        - key: app-cert
          objectName: app-cert
  parameters:
    usePodIdentity: "false"
    keyvaultName: {{ required "A valid .Values.secrets.keyvaultName entry required!" (index (.Values.secrets) "keyvaultName") }}
    tenantId: {{ required "A valid .Values.secrets.tenantId entry required!" (index (.Values.secrets) "tenantId") }}
    objects: |
      array:
        - |
          objectName: app-name
          objectType: secret
        - |
          objectName: app-id
          objectType: secret
        - |
          objectName: app-cert
          objectType: secret
        - |
          objectName: app-cert
          objectType: key
          objectAlias: publickey.pem
        - |
          objectName: ini-client-cert
          objectType: secret
          objectFormat: pfx
          objectEncoding: base64
          objectAlias: A1GTW-INI.pfx