{{- if not .Values.serviceAccountName }}
{{- include "govway_fse_gtw.validateCloudProvider" . }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- if or .Values.serviceAccount.annotations (eq .Values.cloudProvider "aws") }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
    {{- if eq .Values.cloudProvider "aws" }}
    eks.amazonaws.com/role-arn: {{ .Values.secrets.iamrole }}
    {{- end }}
  {{- end }}
{{- end }}