{{- include "govway_fse_gtw.validateCloudProvider" . }}
{{- if index .Values.providerConfig .Values.cloudProvider "routeEnabled" }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}-gw-console
  labels:
    {{- include "govway_fse_gtw.labels" . | nindent 4 }}
spec:
  path: /govwayConsole
  port:
    targetPort: {{ .Values.govway_fse_gtw.port }}-{{ .Values.govway_fse_gtw.protocol | lower }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "govway_fse_gtw.fullname" . }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}-gw-monitor
  labels:
    {{- include "govway_fse_gtw.labels" . | nindent 4 }}
spec:
  path: /govwayMonitor
  port:
    targetPort: {{ .Values.govway_fse_gtw.port }}-{{ .Values.govway_fse_gtw.protocol | lower }}
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "govway_fse_gtw.fullname" . }}
{{- end }}
