{{- include "govway_fse_gtw.validateCloudProvider" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "govway_fse_gtw.fullname" . }}
  labels:
    {{- include "govway_fse_gtw.labels" . | nindent 4 }}
{{- if or .Values.service.annotations (eq .Values.cloudProvider "aws") }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}  
    {{- end }}

{{- end }}
spec:
  type: {{ index .Values.providerConfig .Values.cloudProvider "serviceType" | default .Values.service.type }}
  {{- if eq .Values.cloudProvider "aws" }}
  ports:
    {{- /* Genero un numero casuale compreso tra 30000 e 32767 da utilizzare come nodeport */ -}}  
    {{- $randomNodePort := add (mod (randNumeric 4 | atoi) 2768) 30000 }}
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      nodePort: {{ .Values.service.nodePort | default $randomNodePort }}
  {{- else }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.port }}-{{ .Values.service.protocol | lower }}
  {{- end }}
  selector:
    {{- include "govway_fse_gtw.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
